default_language_version:
  python: "python3.11"


repos:

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.6.0"
    hooks:
      - id: "check-added-large-files"
      - id: "check-vcs-permalinks"
      - id: "end-of-file-fixer"

  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    rev: "v0.4.2"
    hooks:
      - id: "ruff"
        # NOTE: "--exit-non-zero-on-fix" is important for CI to function
        # correctly!
        args: ["--fix", "--exit-non-zero-on-fix"]

  - repo: "https://github.com/psf/black"
    rev: "24.4.2"
    hooks:
      - id: "black"

  - repo: "https://github.com/shellcheck-py/shellcheck-py"
    rev: "v0.10.0.1"
    hooks:
      - id: "shellcheck"
        args: ["-x"]
